### PR TITLE
Crramirez/fix/explorer

### PR DESCRIPTION
**Pull request by crramirez**

### CODE REVIEW

**Comment by grufwub** [comment]
Looks all good to me and runs fine on my machine :+1:. Before merge, adding a commit to delete `getexecpath` in common.sh since it isn't used anymore, and commenting-out `getexecname` until we figure out that situation might be worth doing. What do you think?

**Comment by crramirez** [comment]
Sound good to me

**Comment by grufwub** [comment]
Made that change now if you want to make one final check and merge @crramirez

**Comment by crramirez** [comment]
Looks good

**Pull request merged**
